### ISSUE TITLE
Using Docker

### ISSUE THREAD

**Issue by QazQazaq** [floleuerer/fastai_ulmfit#1]
How to use Docker in Python.

**Comment by floleuerer** [comment]
I am not sure what you mean with "use Docker in Python". I guess your question is related to the wikiextractor scripts. You can try to install wikiextracotr `pip install wikiextractor`) and run the `preprocess.py` manually. I created the Docker image because it was hard to get wikiextractor set up correctly (and reproducable). If you run in trouble I unfortunately can't help because that's why I created the docker image.

https://github.com/floleuerer/fastai_ulmfit/blob/main/we/app/preprocess.py

Florian
